name: Build Raspberry Pi OS with BIND9

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Packer build
        uses: enr0s/packer-qemu-action@v1.0
        with:
          templateFile: 'raspbian-with-bind9.pkr.hcl'
          workingDir: '.'

      # - name: Initialize Packer plugins
      #   run: packer init -upgrade raspbian-with-bind9.pkr.hcl
  
      # - name: Build Raspberry Pi OS image
      #   run: |
      #     packer build raspbian-with-bind9.pkr.hcl

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: raspbian-image
          path: output-arm64/*.img

          