name: Build Raspberry Pi OS with BIND9

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Packer
        run: |
          curl -fsSL https://releases.hashicorp.com/packer/1.9.4/packer_1.9.4_linux_amd64.zip -o packer.zip
          sudo unzip -o packer.zip -d /usr/local/bin
          rm packer.zip

      - name: Configure QEMU
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-user-static

      - name: Set up Packer GitHub API Token
        run: echo "PACKER_GITHUB_API_TOKEN=${{ secrets.PACKER_GITHUB_API_TOKEN }}" >> $GITHUB_ENV
  

      - name: Initialize Packer plugins
        run: packer init -upgrade raspbian-with-bind9.pkr.hcl
  
      - name: Build Raspberry Pi OS image
        run: |
          packer build raspbian-with-bind9.pkr.hcl

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: raspbian-image
          path: output-arm64/*.img

          